name: Code Quality workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-testing:
    name: Vitest unit testing
    runs-on: ubuntu-24.04

    steps:
      - name: Code Checkout
        uses: "actions/checkout@v4"

      - name: Pnpm Installation
        uses: pnpm/action-setup@v3
        with:
            version: 9.x

      - name: NodeJS Initialization
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'pnpm'

      - name: Dependencies Installation
        run: pnpm i
        shell: bash

      - name: Seeding Variable Creation
        run: echo "CURRENT_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Tests Run With Seeding
        run: pnpm run test:unit --sequence.seed=$CURRENT_TIME

  code-formatting:
    name: Prettier code formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Code Checkout
        uses: "actions/checkout@v4"

      - name: Pnpm Installation
        uses: pnpm/action-setup@v3
        with:
            version: 9.x

      - name: NodeJS Initialization
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'pnpm'

      - name: Dependencies Installation
        run: pnpm i
        shell: bash

      - name: Code Formatting
        run: pnpm run audit:format

  code-linting:
    name: Eslint code linting
    runs-on: ubuntu-24.04
    steps:
      - name: Code Checkout
        uses: "actions/checkout@v4"

      - name: Pnpm Installation
        uses: pnpm/action-setup@v3
        with:
            version: 9.x

      - name: NodeJS Initialization
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'pnpm'

      - name: Dependencies Installation
        run: pnpm i
        shell: bash

      - name: Code Linting
        run: pnpm run audit:lint

  code-build:
    name: Build code
    runs-on: ubuntu-24.04
    steps:
      - name: Code Checkout
        uses: "actions/checkout@v4"

      - name: Pnpm Installation
        uses: pnpm/action-setup@v3
        with:
            version: 9.x

      - name: NodeJS Initialization
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'pnpm'

      - name: Dependencies Installation
        run: pnpm i
        shell: bash

      - name: Build Code
        run: pnpm run build